package com.forestrytracker;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.NpcID;
import net.runelite.api.gameval.ObjectID;

/**
 * The nine Forestry events, with lookups from the NPC and GameObject ids that make them up.
 * Ids mirror those used by RuneLite's core Woodcutting plugin.
 */
@Getter
@RequiredArgsConstructor
public enum ForestryEvent
{
	RISING_ROOTS("Rising Roots"),
	STRUGGLING_SAPLING("Struggling Sapling"),
	FLOWERING_TREE("Flowering Tree"),
	LEPRECHAUN("Leprechaun"),
	POACHERS("Poachers"),
	PHEASANT_CONTROL("Pheasant Control"),
	BEE_HIVE("Bee Hive"),
	ENCHANTMENT_RITUAL("Enchantment Ritual"),
	FRIENDLY_ENT("Friendly Ent");

	private final String displayName;

	/**
	 * @return the event an NPC belongs to, or null if the NPC is not part of a Forestry event
	 */
	public static ForestryEvent fromNpcId(int id)
	{
		switch (id)
		{
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL01:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL02:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL03:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL04:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL05:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL06:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL07:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_COL08:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL01:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL02:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL03:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL04:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL05:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL06:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL07:
			case NpcID.GATHERING_EVENT_FLOWERING_TREE_BUSH_FRUITED_COL08:
				// Note: GATHERING_EVENT_FLOWERING_TREE_BEES is deliberately NOT mapped. Despite its name the
				// bees NPC also appears during the Bee Hive event, so it would misidentify that event.
				return FLOWERING_TREE;

			case NpcID.GATHERING_EVENT_WOODCUTTING_LEPRECHAUN:
				return LEPRECHAUN;

			case NpcID.GATHERING_EVENT_POACHERS_FOX_OUTDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_FOX_INDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_TRAP:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER01_OUTDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER02_OUTDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER03_OUTDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER01_INDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER02_INDOORS:
			case NpcID.GATHERING_EVENT_POACHERS_POACHER03_INDOORS:
				return POACHERS;

			case NpcID.GATHERING_EVENT_PHEASANT_FORESTER:
			case NpcID.GATHERING_EVENT_PHEASANT:
				return PHEASANT_CONTROL;

			case NpcID.GATHERING_EVENT_BEES_BEEKEEPER:
			case NpcID.GATHERING_EVENT_BEES_BEEBOX_1:
			case NpcID.GATHERING_EVENT_BEES_BEEBOX_2:
			case NpcID.GATHERING_EVENT_BEES_BEEBOX_3:
			case NpcID.GATHERING_EVENT_BEES_BEEBOX_4:
				return BEE_HIVE;

			case NpcID.GATHERING_EVENT_ENCHANTED_RITUAL_DRYAD:
				return ENCHANTMENT_RITUAL;

			case NpcID.GATHERING_EVENT_ENTLINGS_NPC_01:
			case NpcID.GATHERING_EVENT_ENTLINGS_NPC_01_PRUNED:
				return FRIENDLY_ENT;

			default:
				if (id >= NpcID.GATHERING_EVENT_ENCHANTED_RITUAL_A_1 && id <= NpcID.GATHERING_EVENT_ENCHANTED_RITUAL_D_4)
				{
					return ENCHANTMENT_RITUAL;
				}
				return null;
		}
	}

	/**
	 * @return the event a GameObject belongs to, or null if the object is not part of a Forestry event
	 */
	public static ForestryEvent fromObjectId(int id)
	{
		switch (id)
		{
			case ObjectID.GATHERING_EVENT_RISING_ROOTS:
			case ObjectID.GATHERING_EVENT_RISING_ROOTS_SPECIAL:
				return RISING_ROOTS;

			case ObjectID.GATHERING_EVENT_SAPLING_1X1:
			case ObjectID.GATHERING_EVENT_SAPLING_WITHERING_1X1:
			case ObjectID.GATHERING_EVENT_SAPLING_SAVED_1X1:
			case ObjectID.GATHERING_EVENT_SAPLING_2X2:
			case ObjectID.GATHERING_EVENT_SAPLING_WITHERING_2X2:
			case ObjectID.GATHERING_EVENT_SAPLING_SAVED_2X2:
			case ObjectID.GATHERING_EVENT_SAPLING_3X3:
			case ObjectID.GATHERING_EVENT_SAPLING_WITHERING_3X3:
			case ObjectID.GATHERING_EVENT_SAPLING_SAVED_3X3:
			case ObjectID.GATHERING_EVENT_SAPLING_4X4:
			case ObjectID.GATHERING_EVENT_SAPLING_WITHERING_4X4:
			case ObjectID.GATHERING_EVENT_SAPLING_SAVED_4X4:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_1:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_2:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_3:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_4A:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_4B:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_4C:
			case ObjectID.GATHERING_EVENT_SAPLING_INGREDIENT_5:
				return STRUGGLING_SAPLING;

			case ObjectID.GATHERING_EVENT_WOODCUTTING_LEPRECHAUN_RAINBOW:
			case ObjectID.GATHERING_EVENT_WOODCUTTING_LEPRECHAUN_CLOVER:
				return LEPRECHAUN;

			case ObjectID.GATHERING_EVENT_PHEASANT_NEST01:
			case ObjectID.GATHERING_EVENT_PHEASANT_NEST02:
				return PHEASANT_CONTROL;

			case ObjectID.GATHERING_EVENT_BEES_BEEHIVE01:
				return BEE_HIVE;

			default:
				return null;
		}
	}
}
